micronaut:
  application:
    name: keyManager
  http:
    client:
      logger-name: mylogger
    services:
      itauERP:
        logger-name: itauERP
        urls:
          - 'http://${ITAU_ERP_HOSTNAME:localhost}:${ITAU_ERP_PORT:9091}'
      bacenPix:
        logger-name: bacenPix
        urls:
          - 'http://${BACEN_HOSTNAME:localhost}:${BACEN_PORT:8082}'

datasources:
  default:
    url: 'jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_NAME:keyManagerPix}'
    driverClassName: org.postgresql.Driver
    username: '${DB_USERNAME:postgres}'
    password: '${DB_PASSWORD:123456}'
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
