apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-itau-erp
spec:
  selector:
    matchLabels:
      app: deploy-itau-erp
  template:
    metadata:
      labels:
        app: deploy-itau-erp
    spec:
      containers:
      - name: deploy-itau-erp
        image: public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp
        ports:
        - containerPort: 9091
